package Route.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum Direction {
  north("north", 1),
  south("south", 3),
  east("east", 2),
  west("west", 4);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final int myValue;
  Direction(String name, int value) {
    myName = name;
    myValue = value;
  }
  public int getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Integer.toString(myValue);
  }
  public static List<Direction> getConstants() {
    List<Direction> list = ListSequence.fromList(new LinkedList<Direction>());
    ListSequence.fromList(list).addElement(Direction.north);
    ListSequence.fromList(list).addElement(Direction.south);
    ListSequence.fromList(list).addElement(Direction.east);
    ListSequence.fromList(list).addElement(Direction.west);
    return list;
  }
  public static Direction getDefault() {
    return Direction.north;
  }
  public static Direction parseValue(String value) {
    if (value == null) {
      return Direction.getDefault();
    }
    if (value.equals(Direction.north.getValueAsString())) {
      return Direction.north;
    }
    if (value.equals(Direction.south.getValueAsString())) {
      return Direction.south;
    }
    if (value.equals(Direction.east.getValueAsString())) {
      return Direction.east;
    }
    if (value.equals(Direction.west.getValueAsString())) {
      return Direction.west;
    }
    return Direction.getDefault();
  }
}
