package Route.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum TurnDirection {
  left("left", 0),
  right("right", 1);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final int myValue;
  TurnDirection(String name, int value) {
    myName = name;
    myValue = value;
  }
  public int getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Integer.toString(myValue);
  }
  public static List<TurnDirection> getConstants() {
    List<TurnDirection> list = ListSequence.fromList(new LinkedList<TurnDirection>());
    ListSequence.fromList(list).addElement(TurnDirection.left);
    ListSequence.fromList(list).addElement(TurnDirection.right);
    return list;
  }
  public static TurnDirection getDefault() {
    return TurnDirection.left;
  }
  public static TurnDirection parseValue(String value) {
    if (value == null) {
      return TurnDirection.getDefault();
    }
    if (value.equals(TurnDirection.left.getValueAsString())) {
      return TurnDirection.left;
    }
    if (value.equals(TurnDirection.right.getValueAsString())) {
      return TurnDirection.right;
    }
    return TurnDirection.getDefault();
  }
}
