package Route.generator.Route;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.generator.template.IfMacroContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_2278735731919536626(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0x7d459d9437245fcfL, "x"));
  }
  public static Object propertyMacro_GetPropertyValue_2278735731919536639(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0x7d459d9437245fd2L, "y"));
  }
  public static Object propertyMacro_GetPropertyValue_2278735731919536655(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0x7d459d9437245fd2L, "y"));
  }
  public static Object propertyMacro_GetPropertyValue_2278735731919536676(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0x7d459d9437245fd7L, "width"));
  }
  public static Object propertyMacro_GetPropertyValue_2278735731919536689(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0x7d459d9437245fdeL, "height"));
  }
  public static Object propertyMacro_GetPropertyValue_2278735731919536703(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0xdd22d76a1376dc6L, "robot")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0xdd22d76a134dcc1L, 0xdd22d76a134dcdfL, "x"));
  }
  public static Object propertyMacro_GetPropertyValue_2278735731919536718(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0xdd22d76a1376dc6L, "robot")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0xdd22d76a134dcc1L, 0xdd22d76a134dce1L, "y"));
  }
  public static Object propertyMacro_GetPropertyValue_2278735731919536734(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger_def(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0xdd22d76a1376dc6L, "robot")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0xdd22d76a134dcc1L, 0xdd22d76a134de7eL, "heading"), "1");
  }
  public static Object propertyMacro_GetPropertyValue_995908455136761186(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0x7d459d9437245fcfL, "x"));
  }
  public static Object propertyMacro_GetPropertyValue_995908455136780627(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0x7d459d9437245fd2L, "y"));
  }
  public static Object propertyMacro_GetPropertyValue_995908455136797236(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0x7d459d9437245fd7L, "width"));
  }
  public static Object propertyMacro_GetPropertyValue_995908455136813237(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0x7d459d9437245fdeL, "height"));
  }
  public static Object propertyMacro_GetPropertyValue_2278735731917814884(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0x7d459d9437245fd2L, "y"));
  }
  public static Object propertyMacro_GetPropertyValue_2278735731917883767(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0x7d459d9437245fd2L, "y"));
  }
  public static Object propertyMacro_GetPropertyValue_995908455137974934(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0xdd22d76a134db48L, "Route.structure.Forward")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0xdd22d76a134db48L, 0xdd22d76a134db64L, "distance"));
  }
  public static Object propertyMacro_GetPropertyValue_2278735731918256282(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger_def(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0xdd22d76a134db66L, "Route.structure.Turn")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0xdd22d76a134db66L, 0xdd22d76a134dc52L, "direction"), "0");
  }
  public static Object propertyMacro_GetPropertyValue_995908455139037658(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0x7d459d9437245fcfL, "x"));
  }
  public static Object propertyMacro_GetPropertyValue_995908455139065292(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0x7d459d9437245fd2L, "y"));
  }
  public static Object propertyMacro_GetPropertyValue_2278735731917742746(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0x7d459d9437245fd2L, "y"));
  }
  public static Object propertyMacro_GetPropertyValue_995908455139080913(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0x7d459d9437245fd7L, "width"));
  }
  public static Object propertyMacro_GetPropertyValue_995908455139099538(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0x7d459d9437245fdeL, "height"));
  }
  public static Object propertyMacro_GetPropertyValue_995908455137229300(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0xdd22d76a1376dc6L, "robot")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0xdd22d76a134dcc1L, 0xdd22d76a134dcdfL, "x"));
  }
  public static Object propertyMacro_GetPropertyValue_995908455137278578(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0xdd22d76a1376dc6L, "robot")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0xdd22d76a134dcc1L, 0xdd22d76a134dce1L, "y"));
  }
  public static Object propertyMacro_GetPropertyValue_2278735731918206734(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger_def(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0xdd22d76a1376dc6L, "robot")), MetaAdapterFactory.getProperty(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0xdd22d76a134dcc1L, 0xdd22d76a134de7eL, "heading"), "1");
  }
  public static Object propertyMacro_GetPropertyValue_9026794288039416967(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static boolean ifMacro_Condition_995908455137817241(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(_context.getNode(), MetaAdapterFactory.getConcept(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0xdd22d76a134db48L, "Route.structure.Forward"));
  }
  public static boolean ifMacro_Condition_995908455137836818(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(_context.getNode(), MetaAdapterFactory.getConcept(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0xdd22d76a134db66L, "Route.structure.Turn"));
  }
  public static Iterable<SNode> sourceNodesQuery_995908455137714437(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d94371a2275L, 0x7d459d9437246027L, "borders")), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0x7d459d9437245f18L, 0xdd22d76a1376dc6L, "robot")), MetaAdapterFactory.getContainmentLink(0xba1a442e6df4098L, 0x83cba42e17c80f15L, 0xdd22d76a134dcc1L, 0xdd22d76a134dcddL, "steps"));
  }
}
